### ISSUE TITLE
revert changes to click decorators after click/mypy conflicts resolved

### ISSUE THREAD

**Issue by ghukill** [MITLibraries/transmogrifier#92]
While updating dependencies, PR https://github.com/MITLibraries/transmogrifier/pull/91 also reworked the order of `click` decorators to address a new, [external conflict](https://github.com/pallets/click/issues/2558) between `click==8.1.3` and `mypy==1.4.1`.

This underlying conflict was discovered _after_ the code change, and it's assumed a fix will be rolled out to `click` in the near future that will allow the previous decorator order while also aligning with `mypy` linting, as many others have encountered this as well.

Proposing to revert the `click` decorators to match other projects (with `@click.command` as the top-most decorator, with others following) once it's been determined that `click` and `mypy` are aligned.

Current:
```python
@click.option(
    "-i",
    "--input-file",
    required=True,
    help="Filepath for harvested input records to transform",
)
@click.option(
    "-o",
    "--output-file",
    required=True,
    help="Filepath to write output TIMDEX JSON records to",
)
@click.option(
    "-s",
    "--source",
    required=True,
    type=click.Choice(list(SOURCES.keys()), case_sensitive=False),
    help="Source records were harvested from, must choose from list of options",
)
@click.option(
    "-v", "--verbose", is_flag=True, help="Pass to log at debug level instead of info"
)
@click.command()
def main(source, input_file, output_file, verbose):
...
```

Proposed **reverted** ordering, matching convention in other projects:
```python
@click.command()
@click.option(
    "-i",
    "--input-file",
    required=True,
    help="Filepath for harvested input records to transform",
)
@click.option(
    "-o",
    "--output-file",
    required=True,
    help="Filepath to write output TIMDEX JSON records to",
)
@click.option(
    "-s",
    "--source",
    required=True,
    type=click.Choice(list(SOURCES.keys()), case_sensitive=False),
    help="Source records were harvested from, must choose from list of options",
)
@click.option(
    "-v", "--verbose", is_flag=True, help="Pass to log at debug level instead of info"
)
def main(source, input_file, output_file, verbose):
...
```

**Comment by ehanson8** [comment]
https://github.com/MITLibraries/alma-sapinvoices is also affected by this issue and the `click` version will need to be unpinned when the incompatibility is resolved
